version: "3.7"

services:
  webserver:
    image: nginx:alpine
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - ".:/mnt/api"
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - nodejs

  nodejs:
    build: docker/nodejs
    working_dir: /mnt/api
    container_name: ${APP}-node
    volumes:
      - ".:/mnt/api"

  redis:
    image: redis:alpine
    container_name: ${APP}-redis

  adminredis:
    image: erikdubbelboer/phpredisadmin
    container_name: ${APP}-admin-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=MyRedis
    ports:
      - "8091:80"
